### ISSUE TITLE
Unable to clone repository 

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/crtm#22]
```
Downloading src/Build/CMakeFiles/3.17.1/CMakeDetermineCompilerABI_Fortran.bin (803 KB)
Error downloading object: src/Build/CMakeFiles/3.17.1/CMakeDetermineCompilerABI_Fortran.bin (1459d4a): Smudge error: Error downloading src/Build/CMakeFiles/3.17.1/CMakeDetermineCompilerABI_Fortran.bin (1459d4a96c146edcaf484f8a4230cc1dfa26cf798ac6f30179f954d669042e76): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /Users/KIG/Desktop/crtm-v2.4.0/.git/lfs/logs/20220218T120023.172711.log
```

git-lfs over the limit. What is git-lfs downloading here? I think I just want the source code.

**Comment by BenjaminTJohnson** [comment]
@kgerheiser  github repositories have data limitations using git-lfs, and we're required to purchase "data packs" to support additional bandwidth.  That's being worked currently   I'm working on a solution to use an alternative data provider source.  

We use `git-lfs` for the binary files (i.e., everything in the `/fix/` directory.).  For CRTM, this is a substantial volume (a few GB).  

You should still get the source code, typically it just downloads the pointers to the LFS files, rather than the files themselves when this type of error occurs.  Let me know if that's not occurring. 

Tagging @ytremolet @rhoneyager  for visibility.

**Comment by climbfuji** [comment]
Thanks @BenjaminTJohnson - yes, we need to fix this as soon as possible.

**Comment by kgerheiser** [comment]
I was able to workaround this issue with `export GIT_LFS_SKIP_SMUDGE=1`

**Comment by BenjaminTJohnson** [comment]
By default, every binary file is added to git-lfs because of the `.gitattributes` file.

**Comment by BenjaminTJohnson** [comment]
@kgerheiser quick question for you, are you able to use ectools (ecbuild) now for building / compiling code?

**Comment by kgerheiser** [comment]
I'm actually using the EMC branch which doesn't use ecbuild.
